name: Build Kernel Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            bc \
            bison \
            flex \
            libssl-dev \
            libelf-dev \
            libncurses-dev \
            dwarves \
            cpio \
            kmod \
            gcc-aarch64-linux-gnu \
            gcc-x86-64-linux-gnu \
            binutils-x86-64-linux-gnu

      - name: Build Image
        run: |
          rm -f scripts/basic/fixdep
          rm -f scripts/kconfig/conf
          rm -f scripts/genksyms/genksyms

          sudo ln -sf /usr/bin/x86_64-linux-gnu-ld /usr/local/bin/ld
          sudo ln -sf /usr/bin/x86_64-linux-gnu-gcc /usr/local/bin/hostgcc

          make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- \
            HOSTCC=x86_64-linux-gnu-gcc \
            HOSTCXX=x86_64-linux-gnu-g++ \
            HOSTLD=x86_64-linux-gnu-ld \
            HOSTAR=x86_64-linux-gnu-ar \
            HOST_EXTRACFLAGS="-I/usr/include" \
            olddefconfig

          make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- \
            HOSTCC=x86_64-linux-gnu-gcc \
            HOSTCXX=x86_64-linux-gnu-g++ \
            HOSTLD=x86_64-linux-gnu-ld \
            HOSTAR=x86_64-linux-gnu-ar \
            prepare

          cp arch/arm64/.config .config

          make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- \
            HOSTCC=x86_64-linux-gnu-gcc \
            HOSTCXX=x86_64-linux-gnu-g++ \
            HOSTLD=x86_64-linux-gnu-ld \
            HOSTAR=x86_64-linux-gnu-ar \
            Image -j$(nproc)

      - name: Upload Image
        uses: actions/upload-artifact@v4
        with:
          name: Image
          path: arch/arm64/boot/Image
